image: node:latest

variables:
  PUBLIC_URL: /scan

cache:
  paths:
  - node_modules

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install        # Install all dependencies
    - npm run build      # Build for prod


  artifacts:
    paths:
      - public
  only:
    - main
