image: node:14

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  script:
    - mv build/* public/
  artifacts:
    paths:
      - public/
  only:
    - main
