image: node:latest

variables:
  PUBLIC_URL: /scan

cache:
  paths:
  - node_modules

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install        # Install all dependencies
    - npm run build      # Build for prod
    - mv public _public  # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public    # Move build files to public dir for Gitlab Pages

  artifacts:
    paths:
      - public
  only:
    - main
